/*DATAMIGRATION 6F9EE268-57C1-49DF-91A6-6AE00B6D8D58*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Bookstore', 'Book';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'ID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'NumberOfPages', 'int';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'BrojStranica', 'int';

GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...

UPDATE
  _Bookstore.Book
SET
  BrojStranica = NumberOfPages
WHERE
  BrojStranica is null;

EXEC Rhetos.DataMigrationApplyMultiple 'Bookstore', 'Book', 'ID,  NumberOfPages';