/*DATAMIGRATION 77793D07-2462-401E-826C-52726D771BF6*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Bookstore', 'Book';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'OriginalTitle', 'nvarchar(256)';

EXEC Rhetos.DataMigrationUse 'Bookstore', 'ForeignBook', 'ID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Bookstore', 'ForeignBook', 'OriginalTitle', 'nvarchar(256)';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...

UPDATE
fb

SET OriginalTitle = b.OriginalTitle
FROM _Bookstore.ForeignBook fb
inner join _Bookstore.Book b ON b.ID = fb.ID


EXEC Rhetos.DataMigrationApplyMultiple 'Bookstore', 'ForeignBook', 'ID,  OriginalTitle';